name: WF_Kartei

on: [push]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Olá, Git!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
